//
//  RYFontHelper.swift
//  RYPoetry
//
//  Created by 王荣庆 on 2017/9/28.
//  Copyright © 2017年 RyukieSama. All rights reserved.
//

import UIKit

class RYFontHelper: NSObject {
    class func getFontstyle(ttfName : String, fontSize : CGFloat) -> UIFont {
//        let familyNames = UIFont.familyNames
//        for familyName in familyNames {
//            print("++++++ " + familyName + " ++++++")
//            let fontNames = UIFont.fontNames(forFamilyName: familyName)
//            for fontName in fontNames {
//                print(fontName)
//            }
//            print("=================================")
//        }
        
        return UIFont(name: "FZZJ-HFXSJW", size: fontSize)!
    }
    
}

/**
 Font is Copperplate-Light
 Font is Copperplate
 Font is Copperplate-Bold
 Font is AppleSDGothicNeo-Thin
 Font is AppleSDGothicNeo-Light
 Font is AppleSDGothicNeo-Regular
 Font is AppleSDGothicNeo-Bold
 Font is AppleSDGothicNeo-SemiBold
 Font is AppleSDGothicNeo-UltraLight
 Font is AppleSDGothicNeo-Medium
 Font is Thonburi
 Font is Thonburi-Light
 Font is Thonburi-Bold
 Font is GillSans-Italic
 Font is GillSans-SemiBold
 Font is GillSans-UltraBold
 Font is GillSans-Light
 Font is GillSans-Bold
 Font is GillSans
 Font is GillSans-SemiBoldItalic
 Font is GillSans-BoldItalic
 Font is GillSans-LightItalic
 Font is MarkerFelt-Thin
 Font is MarkerFelt-Wide
 Font is HiraMaruProN-W4
 Font is CourierNewPS-ItalicMT
 Font is CourierNewPSMT
 Font is CourierNewPS-BoldItalicMT
 Font is CourierNewPS-BoldMT
 Font is KohinoorTelugu-Regular
 Font is KohinoorTelugu-Medium
 Font is KohinoorTelugu-Light
 Font is AvenirNextCondensed-Heavy
 Font is AvenirNextCondensed-MediumItalic
 Font is AvenirNextCondensed-Regular
 Font is AvenirNextCondensed-UltraLightItalic
 Font is AvenirNextCondensed-Medium
 Font is AvenirNextCondensed-HeavyItalic
 Font is AvenirNextCondensed-DemiBoldItalic
 Font is AvenirNextCondensed-Bold
 Font is AvenirNextCondensed-DemiBold
 Font is AvenirNextCondensed-BoldItalic
 Font is AvenirNextCondensed-Italic
 Font is AvenirNextCondensed-UltraLight
 Font is TamilSangamMN
 Font is TamilSangamMN-Bold
 Font is HelveticaNeue-UltraLightItalic
 Font is HelveticaNeue-Medium
 Font is HelveticaNeue-MediumItalic
 Font is HelveticaNeue-UltraLight
 Font is HelveticaNeue-Italic
 Font is HelveticaNeue-Light
 Font is HelveticaNeue-ThinItalic
 Font is HelveticaNeue-LightItalic
 Font is HelveticaNeue-Bold
 Font is HelveticaNeue-Thin
 Font is HelveticaNeue-CondensedBlack
 Font is HelveticaNeue
 Font is HelveticaNeue-CondensedBold
 Font is HelveticaNeue-BoldItalic
 Font is GurmukhiMN-Bold
 Font is GurmukhiMN
 Font is Georgia-BoldItalic
 Font is Georgia-Italic
 Font is Georgia
 Font is Georgia-Bold
 Font is TimesNewRomanPS-ItalicMT
 Font is TimesNewRomanPS-BoldItalicMT
 Font is TimesNewRomanPS-BoldMT
 Font is TimesNewRomanPSMT
 Font is SinhalaSangamMN-Bold
 Font is SinhalaSangamMN
 Font is ArialRoundedMTBold
 Font is Kailasa-Bold
 Font is Kailasa
 Font is KohinoorDevanagari-Regular
 Font is KohinoorDevanagari-Light
 Font is KohinoorDevanagari-Semibold
 Font is KohinoorBangla-Regular
 Font is KohinoorBangla-Semibold
 Font is KohinoorBangla-Light
 Font is ChalkboardSE-Bold
 Font is ChalkboardSE-Light
 Font is ChalkboardSE-Regular
 Font is AppleColorEmoji
 Font is PingFangTC-Regular
 Font is PingFangTC-Thin
 Font is PingFangTC-Medium
 Font is PingFangTC-Semibold
 Font is PingFangTC-Light
 Font is PingFangTC-Ultralight
 Font is GujaratiSangamMN
 Font is GujaratiSangamMN-Bold
 Font is GeezaPro-Bold
 Font is GeezaPro
 Font is DamascusBold
 Font is DamascusLight
 Font is Damascus
 Font is DamascusMedium
 Font is DamascusSemiBold
 Font is Noteworthy-Bold
 Font is Noteworthy-Light
 Font is Avenir-Oblique
 Font is Avenir-HeavyOblique
 Font is Avenir-Heavy
 Font is Avenir-BlackOblique
 Font is Avenir-BookOblique
 Font is Avenir-Roman
 Font is Avenir-Medium
 Font is Avenir-Black
 Font is Avenir-Light
 Font is Avenir-MediumOblique
 Font is Avenir-Book
 Font is Avenir-LightOblique
 Font is DiwanMishafi
 Font is AcademyEngravedLetPlain
 Font is Futura-CondensedExtraBold
 Font is Futura-Medium
 Font is Futura-Bold
 Font is Futura-CondensedMedium
 Font is Futura-MediumItalic
 Font is PartyLetPlain
 Font is KannadaSangamMN-Bold
 Font is KannadaSangamMN
 Font is ArialHebrew-Bold
 Font is ArialHebrew-Light
 Font is ArialHebrew
 Font is Farah
 Font is Arial-BoldMT
 Font is Arial-BoldItalicMT
 Font is Arial-ItalicMT
 Font is ArialMT
 Font is Chalkduster
 Font is Kefa-Regular
 Font is HoeflerText-Italic
 Font is HoeflerText-Black
 Font is HoeflerText-Regular
 Font is HoeflerText-BlackItalic
 Font is Optima-ExtraBlack
 Font is Optima-BoldItalic
 Font is Optima-Italic
 Font is Optima-Regular
 Font is Optima-Bold
 Font is Palatino-Italic
 Font is Palatino-Roman
 Font is Palatino-BoldItalic
 Font is Palatino-Bold
 Font is MalayalamSangamMN-Bold
 Font is MalayalamSangamMN
 Font is AlNile
 Font is AlNile-Bold
 Font is LaoSangamMN
 Font is BradleyHandITCTT-Bold
 Font is HiraMinProN-W3
 Font is HiraMinProN-W6
 Font is PingFangHK-Medium
 Font is PingFangHK-Thin
 Font is PingFangHK-Regular
 Font is PingFangHK-Ultralight
 Font is PingFangHK-Semibold
 Font is PingFangHK-Light
 Font is Helvetica-Oblique
 Font is Helvetica-BoldOblique
 Font is Helvetica
 Font is Helvetica-Light
 Font is Helvetica-Bold
 Font is Helvetica-LightOblique
 Font is Courier-BoldOblique
 Font is Courier-Oblique
 Font is Courier
 Font is Courier-Bold
 Font is Cochin-Italic
 Font is Cochin-Bold
 Font is Cochin
 Font is Cochin-BoldItalic
 Font is TrebuchetMS-Bold
 Font is TrebuchetMS-Italic
 Font is Trebuchet-BoldItalic
 Font is TrebuchetMS
 Font is DevanagariSangamMN
 Font is DevanagariSangamMN-Bold
 Font is OriyaSangamMN
 Font is OriyaSangamMN-Bold
 Font is SnellRoundhand
 Font is SnellRoundhand-Bold
 Font is SnellRoundhand-Black
 Font is ZapfDingbatsITC
 Font is BodoniSvtyTwoITCTT-Bold
 Font is BodoniSvtyTwoITCTT-BookIta
 Font is BodoniSvtyTwoITCTT-Book
 Font is Verdana-Italic
 Font is Verdana
 Font is Verdana-Bold
 Font is Verdana-BoldItalic
 Font is AmericanTypewriter-CondensedBold
 Font is AmericanTypewriter-Condensed
 Font is AmericanTypewriter-CondensedLight
 Font is AmericanTypewriter
 Font is AmericanTypewriter-Bold
 Font is AmericanTypewriter-Semibold
 Font is AmericanTypewriter-Light
 Font is AvenirNext-Medium
 Font is AvenirNext-DemiBoldItalic
 Font is AvenirNext-DemiBold
 Font is AvenirNext-HeavyItalic
 Font is AvenirNext-Regular
 Font is AvenirNext-Italic
 Font is AvenirNext-MediumItalic
 Font is AvenirNext-UltraLightItalic
 Font is AvenirNext-BoldItalic
 Font is AvenirNext-Heavy
 Font is AvenirNext-Bold
 Font is AvenirNext-UltraLight
 Font is Baskerville-SemiBoldItalic
 Font is Baskerville-SemiBold
 Font is Baskerville-BoldItalic
 Font is Baskerville
 Font is Baskerville-Bold
 Font is Baskerville-Italic
 Font is KhmerSangamMN
 Font is Didot-Bold
 Font is Didot
 Font is Didot-Italic
 Font is SavoyeLetPlain
 Font is BodoniOrnamentsITCTT
 Font is Symbol
 Font is Menlo-BoldItalic
 Font is Menlo-Bold
 Font is Menlo-Italic
 Font is Menlo-Regular
 Font is NotoNastaliqUrdu
 Font is BodoniSvtyTwoSCITCTT-Book
 Font is Papyrus-Condensed
 Font is Papyrus
 Font is HiraginoSans-W3
 Font is HiraginoSans-W6
 Font is PingFangSC-Medium
 Font is PingFangSC-Semibold
 Font is PingFangSC-Light
 Font is PingFangSC-Ultralight
 Font is PingFangSC-Regular
 Font is PingFangSC-Thin
 Font is MyanmarSangamMN
 Font is MyanmarSangamMN-Bold
 Font is Zapfino
 Font is BodoniSvtyTwoOSITCTT-BookIt
 Font is BodoniSvtyTwoOSITCTT-Book
 Font is BodoniSvtyTwoOSITCTT-Bold
 Font is EuphemiaUCAS
 Font is EuphemiaUCAS-Italic
 Font is EuphemiaUCAS-Bold
 */
/**
 Font is Copperplate-Light
 Font is Copperplate
 Font is Copperplate-Bold
 Font is AppleSDGothicNeo-Thin
 Font is AppleSDGothicNeo-Light
 Font is AppleSDGothicNeo-Regular
 Font is AppleSDGothicNeo-Bold
 Font is AppleSDGothicNeo-SemiBold
 Font is AppleSDGothicNeo-UltraLight
 Font is AppleSDGothicNeo-Medium
 Font is Thonburi
 Font is Thonburi-Light
 Font is Thonburi-Bold
 Font is GillSans-Italic
 Font is GillSans-SemiBold
 Font is GillSans-UltraBold
 Font is GillSans-Light
 Font is GillSans-Bold
 Font is GillSans
 Font is GillSans-SemiBoldItalic
 Font is GillSans-BoldItalic
 Font is GillSans-LightItalic
 Font is MarkerFelt-Thin
 Font is MarkerFelt-Wide
 Font is HiraMaruProN-W4
 Font is CourierNewPS-ItalicMT
 Font is CourierNewPSMT
 Font is CourierNewPS-BoldItalicMT
 Font is CourierNewPS-BoldMT
 Font is KohinoorTelugu-Regular
 Font is KohinoorTelugu-Medium
 Font is KohinoorTelugu-Light
 Font is AvenirNextCondensed-Heavy
 Font is AvenirNextCondensed-MediumItalic
 Font is AvenirNextCondensed-Regular
 Font is AvenirNextCondensed-UltraLightItalic
 Font is AvenirNextCondensed-Medium
 Font is AvenirNextCondensed-HeavyItalic
 Font is AvenirNextCondensed-DemiBoldItalic
 Font is AvenirNextCondensed-Bold
 Font is AvenirNextCondensed-DemiBold
 Font is AvenirNextCondensed-BoldItalic
 Font is AvenirNextCondensed-Italic
 Font is AvenirNextCondensed-UltraLight
 Font is TamilSangamMN
 Font is TamilSangamMN-Bold
 Font is HelveticaNeue-UltraLightItalic
 Font is HelveticaNeue-Medium
 Font is HelveticaNeue-MediumItalic
 Font is HelveticaNeue-UltraLight
 Font is HelveticaNeue-Italic
 Font is HelveticaNeue-Light
 Font is HelveticaNeue-ThinItalic
 Font is HelveticaNeue-LightItalic
 Font is HelveticaNeue-Bold
 Font is HelveticaNeue-Thin
 Font is HelveticaNeue-CondensedBlack
 Font is HelveticaNeue
 Font is HelveticaNeue-CondensedBold
 Font is HelveticaNeue-BoldItalic
 Font is GurmukhiMN-Bold
 Font is GurmukhiMN
 Font is Georgia-BoldItalic
 Font is Georgia-Italic
 Font is Georgia
 Font is Georgia-Bold
 Font is TimesNewRomanPS-ItalicMT
 Font is TimesNewRomanPS-BoldItalicMT
 Font is TimesNewRomanPS-BoldMT
 Font is TimesNewRomanPSMT
 Font is SinhalaSangamMN-Bold
 Font is SinhalaSangamMN
 Font is ArialRoundedMTBold
 Font is Kailasa-Bold
 Font is Kailasa
 Font is KohinoorDevanagari-Regular
 Font is KohinoorDevanagari-Light
 Font is KohinoorDevanagari-Semibold
 Font is KohinoorBangla-Regular
 Font is KohinoorBangla-Semibold
 Font is KohinoorBangla-Light
 Font is ChalkboardSE-Bold
 Font is ChalkboardSE-Light
 Font is ChalkboardSE-Regular
 Font is AppleColorEmoji
 Font is PingFangTC-Regular
 Font is PingFangTC-Thin
 Font is PingFangTC-Medium
 Font is PingFangTC-Semibold
 Font is PingFangTC-Light
 Font is PingFangTC-Ultralight
 Font is GujaratiSangamMN
 Font is GujaratiSangamMN-Bold
 Font is GeezaPro-Bold
 Font is GeezaPro
 Font is DamascusBold
 Font is DamascusLight
 Font is Damascus
 Font is DamascusMedium
 Font is DamascusSemiBold
 Font is Noteworthy-Bold
 Font is Noteworthy-Light
 Font is Avenir-Oblique
 Font is Avenir-HeavyOblique
 Font is Avenir-Heavy
 Font is Avenir-BlackOblique
 Font is Avenir-BookOblique
 Font is Avenir-Roman
 Font is Avenir-Medium
 Font is Avenir-Black
 Font is Avenir-Light
 Font is Avenir-MediumOblique
 Font is Avenir-Book
 Font is Avenir-LightOblique
 Font is DiwanMishafi
 Font is AcademyEngravedLetPlain
 Font is Futura-CondensedExtraBold
 Font is Futura-Medium
 Font is Futura-Bold
 Font is Futura-CondensedMedium
 Font is Futura-MediumItalic
 Font is PartyLetPlain
 Font is KannadaSangamMN-Bold
 Font is KannadaSangamMN
 Font is ArialHebrew-Bold
 Font is ArialHebrew-Light
 Font is ArialHebrew
 Font is Farah
 Font is Arial-BoldMT
 Font is Arial-BoldItalicMT
 Font is Arial-ItalicMT
 Font is ArialMT
 Font is Chalkduster
 Font is Kefa-Regular
 Font is HoeflerText-Italic
 Font is HoeflerText-Black
 Font is HoeflerText-Regular
 Font is HoeflerText-BlackItalic
 Font is Optima-ExtraBlack
 Font is Optima-BoldItalic
 Font is Optima-Italic
 Font is Optima-Regular
 Font is Optima-Bold
 Font is Palatino-Italic
 Font is Palatino-Roman
 Font is Palatino-BoldItalic
 Font is Palatino-Bold
 Font is MalayalamSangamMN-Bold
 Font is MalayalamSangamMN
 Font is AlNile
 Font is AlNile-Bold
 Font is LaoSangamMN
 Font is BradleyHandITCTT-Bold
 Font is HiraMinProN-W3
 Font is HiraMinProN-W6
 Font is PingFangHK-Medium
 Font is PingFangHK-Thin
 Font is PingFangHK-Regular
 Font is PingFangHK-Ultralight
 Font is PingFangHK-Semibold
 Font is PingFangHK-Light
 Font is Helvetica-Oblique
 Font is Helvetica-BoldOblique
 Font is Helvetica
 Font is Helvetica-Light
 Font is Helvetica-Bold
 Font is Helvetica-LightOblique
 Font is Courier-BoldOblique
 Font is Courier-Oblique
 Font is Courier
 Font is Courier-Bold
 Font is Cochin-Italic
 Font is Cochin-Bold
 Font is Cochin
 Font is Cochin-BoldItalic
 Font is TrebuchetMS-Bold
 Font is TrebuchetMS-Italic
 Font is Trebuchet-BoldItalic
 Font is TrebuchetMS
 Font is DevanagariSangamMN
 Font is DevanagariSangamMN-Bold
 Font is OriyaSangamMN
 Font is OriyaSangamMN-Bold
 Font is SnellRoundhand
 Font is SnellRoundhand-Bold
 Font is SnellRoundhand-Black
 Font is ZapfDingbatsITC
 Font is BodoniSvtyTwoITCTT-Bold
 Font is BodoniSvtyTwoITCTT-BookIta
 Font is BodoniSvtyTwoITCTT-Book
 Font is Verdana-Italic
 Font is Verdana
 Font is Verdana-Bold
 Font is Verdana-BoldItalic
 Font is AmericanTypewriter-CondensedBold
 Font is AmericanTypewriter-Condensed
 Font is AmericanTypewriter-CondensedLight
 Font is AmericanTypewriter
 Font is AmericanTypewriter-Bold
 Font is AmericanTypewriter-Semibold
 Font is AmericanTypewriter-Light
 Font is AvenirNext-Medium
 Font is AvenirNext-DemiBoldItalic
 Font is AvenirNext-DemiBold
 Font is AvenirNext-HeavyItalic
 Font is AvenirNext-Regular
 Font is AvenirNext-Italic
 Font is AvenirNext-MediumItalic
 Font is AvenirNext-UltraLightItalic
 Font is AvenirNext-BoldItalic
 Font is AvenirNext-Heavy
 Font is AvenirNext-Bold
 Font is AvenirNext-UltraLight
 Font is Baskerville-SemiBoldItalic
 Font is Baskerville-SemiBold
 Font is Baskerville-BoldItalic
 Font is Baskerville
 Font is Baskerville-Bold
 Font is Baskerville-Italic
 Font is KhmerSangamMN
 Font is Didot-Bold
 Font is Didot
 Font is Didot-Italic
 Font is SavoyeLetPlain
 Font is BodoniOrnamentsITCTT
 Font is Symbol
 Font is Menlo-BoldItalic
 Font is Menlo-Bold
 Font is Menlo-Italic
 Font is Menlo-Regular
 Font is NotoNastaliqUrdu
 Font is BodoniSvtyTwoSCITCTT-Book
 Font is Papyrus-Condensed
 Font is Papyrus
 Font is HiraginoSans-W3
 Font is HiraginoSans-W6
 Font is PingFangSC-Medium
 Font is PingFangSC-Semibold
 Font is PingFangSC-Light
 Font is PingFangSC-Ultralight
 Font is PingFangSC-Regular
 Font is PingFangSC-Thin
 Font is MyanmarSangamMN
 Font is MyanmarSangamMN-Bold
 Font is Zapfino
 Font is BodoniSvtyTwoOSITCTT-BookIt
 Font is BodoniSvtyTwoOSITCTT-Book
 Font is BodoniSvtyTwoOSITCTT-Bold
 Font is EuphemiaUCAS
 Font is EuphemiaUCAS-Italic
 Font is EuphemiaUCAS-Bold
 */
