platform :ios, ‘9.0’
# 工程不显示任何警告
inhibit_all_warnings!

use_frameworks!

target 'RYPoetry' do

#pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire', '~> 4.5'
pod 'Kingfisher', '~> 4.0'
pod 'SQLite.swift', '~> 0.11.4'
pod 'LeanCloud', '~> 11.0.0'
pod 'AVOSCloud', '~> 8.0.3'

end
