source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, ‘15.0’
# 工程不显示任何警告
inhibit_all_warnings!

target 'RYPoetry' do

#pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire'
pod 'SQLite.swift', '~> 0.13.3'

end
